import Head from 'next/head';
import Popular from '../components/Popular';
import { useRouter } from 'next/router';

export default function Home() {
  return (
    <>
      <Head>
        <title>Conversion Project: React to Next</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Popular />
      </main>
    </>
  );
}
